### ISSUE TITLE
Can neural prophet use soft-dtw loss function?

### ISSUE THREAD

**Issue by weidongzhou1994** [tslearn-team/tslearn#477]
As title

**Comment by YannCabanes** [comment]
Hello @weidongzhou1994, I think that it is currently not possible.

`NeuralProphet` (https://github.com/ourownstory/neural_prophet/blob/main/neuralprophet/forecaster.py) proposes to use metrics from `PyTorch`. Indeed, the class `NeuralProphet` has the optional parameter `loss_func`:

```
        loss_func : str, torch.nn.functional.loss
            Type of loss to use:

            Options
                * (default) ``Huber``: Huber loss function
                * ``MSE``: Mean Squared Error loss function
                * ``MAE``: Mean Absolute Error loss function
                * ``torch.nn.functional.loss.``: loss or callable for custom loss, eg. L1-Loss

            Examples
            --------
            >>> from neuralprophet import NeuralProphet
            >>> import torch
            >>> import torch.nn as nn
            >>> m = NeuralProphet(loss_func=torch.nn.L1Loss)
```

However, when I run the code:

```
from neuralprophet import NeuralProphet
from tslearn.metrics import SoftDTWLossPyTorch
m = NeuralProphet(loss_func=SoftDTWLossPyTorch)
```

I obtain the following error message:

```
Traceback (most recent call last):
  File "/home/ycabanes/work/tslearn/codes/try_neuralprophet_with_softdtwlosspytorch.py", line 15, in <module>
    m = NeuralProphet(loss_func=SoftDTWLossPyTorch)
  File "/home/ycabanes/.local/lib/python3.8/site-packages/neuralprophet/forecaster.py", line 398, in __init__
    self.config_train = configure.Train(
  File "<string>", line 18, in __init__
  File "/home/ycabanes/.local/lib/python3.8/site-packages/neuralprophet/configure.py", line 112, in __post_init__
    self.set_loss_func()
  File "/home/ycabanes/.local/lib/python3.8/site-packages/neuralprophet/configure.py", line 134, in set_loss_func
    raise NotImplementedError(f"Loss function {self.loss_func} not found")
NotImplementedError: Loss function <class 'tslearn.metrics.soft_dtw_loss_pytorch.SoftDTWLossPyTorch'> not found
```

**Comment by YannCabanes** [comment]
I have succeded to combine the `SoftDTWLossPytorch` from `tslearn` with `NeuralProphet` from `neuralprophet` defining:
```
def soft_dtw_loss_function(x, y, dist_func=SoftDTWLossPyTorch._euclidean_squared_dist, gamma=0.1):
    d_xy = dist_func(x, y)
    return _SoftDTWLossPyTorch.apply(d_xy, gamma)
```

and then:

```
m = NeuralProphet(loss_func=soft_dtw_loss_function)
```

**Comment by anandaheino** [comment]
This helped me and my team a lot! Thank you @YannCabanes
